name: raylib_dartified_unhinged
description: Deterministic playground for constructing realities out of data, structure, and controlled execution.
version: 5.5.1
repository: https://github.com/TheNoiselessNoise/raylib_dartified_unhinged

environment:
  sdk: '^3.10.0'

dependencies:
  meta: ^1.17.0
  path: ^1.9.1
  raylib_dartified_base: '>=5.5.0 <6.0.0'
  raylib_dartified_web: '>=5.5.0 <6.0.0'
  raylib_dartified: '>=5.5.0 <6.0.0'
  uuid: ^4.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.31.2
